
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings$Listener ///

public protocol MainActivityBindings_Listener: JavaProtocol {

    /// public abstract void com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings$Listener.hi()

    func hi()

}


open class MainActivityBindings_ListenerForward: JNIObjectForward, MainActivityBindings_Listener {

    private static var MainActivityBindings_ListenerJNIClass: jclass?

    /// public abstract void com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings$Listener.hi()

    private static var hi_MethodID_2: jmethodID?

    open func hi() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "hi", methodSig: "()V", methodCache: &MainActivityBindings_ListenerForward.hi_MethodID_2, args: &__args, locals: &__locals )
    }


}

private typealias MainActivityBindings_Listener_hi_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jlong ) -> ()

private func MainActivityBindings_Listener_hi_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ __swiftObject: jlong ) -> () {
    MainActivityBindings_ListenerLocal_.swiftObject( jniEnv: __env, javaObject: __this, swiftObject: __swiftObject ).hi( )
}

fileprivate class MainActivityBindings_ListenerLocal_: JNILocalProxy<MainActivityBindings_Listener, Any> {

    fileprivate static let _proxyClass: jclass = {
        var natives = [JNINativeMethod]()

        let MainActivityBindings_Listener_hi_0_thunk: MainActivityBindings_Listener_hi_0_type = MainActivityBindings_Listener_hi_0
        natives.append( JNINativeMethod( name: strdup("__hi"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( MainActivityBindings_Listener_hi_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

        natives.append( JNINativeMethod( name: strdup("__finalize"), signature: strdup("(J)V"), fnPtr: unsafeBitCast( JNIReleasableProxy__finalize_thunk, to: UnsafeMutableRawPointer.self ) ) )

        let clazz = JNI.FindClass( proxyClassName() )
        natives.withUnsafeBufferPointer {
            nativesPtr in
            if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr.baseAddress, jint(nativesPtr.count) ) != jint(JNI_OK) {
                JNI.report( "Unable to register java natives" )
            }
        }

        defer { JNI.DeleteLocalRef( clazz ) }
        return JNI.api.NewGlobalRef( JNI.env, clazz )!
    }()

    override open class func proxyClassName() -> String { return "org/swiftjava/com_millertech/MainActivityBindings_ListenerProxy" }
    override open class func proxyClass() -> jclass? { return _proxyClass }

}

extension MainActivityBindings_Listener {

    public func localJavaObject( _ locals: UnsafeMutablePointer<[jobject]> ) -> jobject? {
        return MainActivityBindings_ListenerLocal_( owned: self, proto: self ).localJavaObject( locals )
    }

}

open class MainActivityBindings_ListenerBase: MainActivityBindings_Listener {

    public init() {}

    /// public abstract void com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings$Listener.hi()

    open func hi() /**/ {
    }


}
