
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings$Responder ///

public protocol MainActivityBindings_Responder: JavaProtocol {

}


open class MainActivityBindings_ResponderForward: JNIObjectForward, MainActivityBindings_Responder {

    private static var MainActivityBindings_ResponderJNIClass: jclass?

}

