
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings$Listener ///

package org.swiftjava.com_millertech;

@SuppressWarnings("JniMissingFunction")
public class MainActivityBindings_ListenerProxy implements com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings.Listener {

    // address of proxy object
    long __swiftObject;

    MainActivityBindings_ListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract void com.millertech.bluetoothexplorer.swiftbindings.MainActivityBindings$Listener.hi()

    public native void __hi( long __swiftObject );

    public void hi() {
        __hi( __swiftObject  );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
