module: Bluetooth
author: PureSwift
github_url: https://github.com/PureSwift/Bluetooth

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Xcode/Bluetooth.xcodeproj, -target, Bluetooth-macOS, LIBRARY_SEARCH_PATHS=.build/debug]