// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BluetoothExplorer",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "BluetoothExplorer",
            targets: ["BluetoothExplorer"],
            teamIdentifier: "3AGB2QANNL",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .bluetoothAlways(purposeString: "Bluetooth is needed to scan for devices.")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/PureSwift/GATT.git", .branch("feature/async"))
    ],
    targets: [
        .executableTarget(
            name: "BluetoothExplorer",
            dependencies: [
                .product(name: "GATT", package: "GATT"),
                .product(name: "DarwinGATT", package: "GATT")
            ],
            path: "."
        )
    ]
)